import React,{useEffect,useRef,useState} from 'react';
import {GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signInWithPhoneNumber,RecaptchaVerifier,signOut,type ConfirmationResult,type User} from 'firebase/auth';
import {type CountryCode} from 'libphonenumber-js';
import {ArrowLeft,ArrowRight,Eye,EyeOff,LoaderCircle,Mail,Phone,ShieldCheck,Check} from 'lucide-react';
import {auth,type PublicConfig} from './api';
import {normalizePhone,authError} from './auth-utils';
import {BrandMark} from './Brand';
type Screen='choices'|'email'|'phone'|'sms'|'reset'|'verify';
export function AuthPanel({config,user,onSuccess,initialMode='login'}:{config:PublicConfig|null;user:User|null;onSuccess:()=>void;initialMode?:'login'|'register'}){
  const [mode,setMode]=useState(initialMode);const [screen,setScreen]=useState<Screen>(user&&!user.emailVerified&&!user.phoneNumber?'verify':'choices');
  const [email,setEmail]=useState(user?.email??'');const [password,setPassword]=useState('');const [visible,setVisible]=useState(false);
  const [country,setCountry]=useState<CountryCode>('MY');const [phone,setPhone]=useState('');const [sentTo,setSentTo]=useState('');const [code,setCode]=useState('');
  const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [consent,setConsent]=useState(false);
  const [seconds,setSeconds]=useState(0);const [verification,setVerification]=useState<ConfirmationResult|null>(null);
  const captchaRef=useRef<HTMLDivElement>(null);const captcha=useRef<RecaptchaVerifier|null>(null);
  useEffect(()=>{const t=setInterval(()=>setSeconds(n=>Math.max(0,n-1)),1000);return()=>{clearInterval(t);captcha.current?.clear();};},[]);
  useEffect(()=>{if(user&&!user.emailVerified&&!user.phoneNumber)setScreen('verify');},[user?.uid]);
  function route(next:Screen){setScreen(next);setError('');setNotice('');}
  function requireAuth(){if(!auth||!config?.auth)throw new Error('Sign-in is not connected yet. You can explore the sample workspace while setup is completed.');return auth;}
  async function perform(name:string,fn:()=>Promise<void>){setBusy(name);setError('');setNotice('');try{await fn();}catch(e){setError(authError(e));}finally{setBusy('');}}
  async function google(){await perform('google',async()=>{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const result=await signInWithPopup(requireAuth(),provider);if(result.user.emailVerified||result.user.phoneNumber)onSuccess();else route('verify');});}
  async function emailSubmit(e:React.FormEvent){e.preventDefault();await perform('email',async()=>{
    const client=requireAuth();
    const result=mode==='register'?await createUserWithEmailAndPassword(client,email,password):await signInWithEmailAndPassword(client,email,password);
    setPassword('');
    if(!result.user.emailVerified){route('verify');if(mode==='register'){await sendEmailVerification(result.user);setSeconds(60);setNotice('Verification email sent.');}}
    else onSuccess();
  });}
  async function sendSMS(e?:React.FormEvent){e?.preventDefault();await perform('sms',async()=>{
    const client=requireAuth();const number=normalizePhone(phone,country);
    const last=Number(sessionStorage.getItem(`lumo-sms-${number}`)??0);const remaining=Math.ceil((last+60000-Date.now())/1000);
    if(remaining>0){setSeconds(remaining);throw new Error(`Please wait ${remaining} seconds before requesting another code.`);}
    captcha.current?.clear();captcha.current=new RecaptchaVerifier(client,captchaRef.current!,{size:'normal'});
    await captcha.current.render();
    const result=await signInWithPhoneNumber(client,number,captcha.current);
    setVerification(result);setSentTo(number);setCode('');sessionStorage.setItem(`lumo-sms-${number}`,String(Date.now()));setSeconds(60);route('sms');
  });}
  async function verifySMS(e:React.FormEvent){e.preventDefault();await perform('verify',async()=>{
    if(!verification)throw new Error('Request a new code to continue.');await verification.confirm(code);onSuccess();
  });}
  const titles:Record<Screen,string>={choices:mode==='login'?'Welcome back.':'Meet your next assistant.',email:mode==='login'?'Log in to Lumo.':'Create your account.',phone:'Your number. Your account.',sms:'Check your messages.',reset:'Reset your password.',verify:'Check your inbox.'};
  return <div className="auth-content">
    {screen!=='choices'&&screen!=='verify'&&<button className="auth-back" type="button" onClick={()=>route(screen==='sms'?'phone':screen==='reset'?'email':'choices')} aria-label="Back"><ArrowLeft size={19}/></button>}
    <a href="/" className="auth-brand" aria-label="Lumo home"><BrandMark/></a>
    <h2>{titles[screen]}</h2><p className="auth-subtitle">{screen==='choices'?'A little less setup. A lot more possibility.':screen==='email'?'Your workspace. Your ideas. All in one place.':screen==='phone'?'We will text you a code to securely sign in.':screen==='sms'?<>Enter the 6-digit code sent to <strong>{sentTo}</strong>.</>:screen==='reset'?'Enter your email to receive a password reset link.':<>Open the verification link sent to <strong>{user?.email||email}</strong>.</>}</p>
    {screen==='choices'&&<><div className="auth-providers"><button className="provider-button" disabled={!!busy} onClick={google}>{busy==='google'?<LoaderCircle className="spin" size={20}/>:<img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" width="20" height="20" alt=""/>}<span>Continue with Google</span></button><button className="provider-button" disabled={!!busy} onClick={()=>route('phone')}><Phone size={19}/><span>Continue with phone</span></button></div><div className="auth-divider"><span>or</span></div><button className="auth-primary" onClick={()=>route('email')}><Mail size={18}/>Continue with email<ArrowRight size={17}/></button><p className="auth-switch">{mode==='login'?'New to Lumo?':'Already have an account?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}}>{mode==='login'?'Create an account':'Log in'}</button></p></>}
    {screen==='email'&&<form className="auth-form" onSubmit={emailSubmit}><label>Email address<input autoFocus type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<div className="password-field"><input type={visible?'text':'password'} autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={mode==='register'?8:1} maxLength={128} required placeholder={mode==='register'?'At least 8 characters':'Enter your password'}/><button type="button" onClick={()=>setVisible(v=>!v)} aria-label={visible?'Hide password':'Show password'} title={visible?'Hide password':'Show password'}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==='login'&&<button type="button" className="auth-forgot" onClick={()=>route('reset')}>Forgot password?</button>}{mode==='register'&&<label className="auth-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to the <a href="/terms" target="_blank" rel="noreferrer">Terms of service</a> and <a href="/privacy" target="_blank" rel="noreferrer">Privacy notice</a>.</span></label>}<button className="auth-primary" disabled={!!busy}>{busy?<LoaderCircle className="spin" size={18}/>:null}{mode==='register'?'Create account':'Continue'}<ArrowRight size={17}/></button><p className="auth-switch">{mode==='login'?'No account yet?':'Already registered?'} <button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}}>{mode==='login'?'Sign up':'Log in'}</button></p></form>}
    {(screen==='phone'||screen==='sms')&&<><form className="auth-form" onSubmit={screen==='phone'?sendSMS:verifySMS}>{screen==='phone'?<><label>Phone number<div className="phone-field"><select aria-label="Country code" value={country} onChange={e=>setCountry(e.target.value as CountryCode)}><option value="MY">MY +60</option><option value="SG">SG +65</option><option value="ID">ID +62</option><option value="GB">GB +44</option><option value="US">US +1</option></select><input autoFocus type="tel" autoComplete="tel-national" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="12 345 6789" required maxLength={22}/></div></label><label className="auth-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree to receive a verification SMS. Message rates may apply. Google processes my phone number for spam and abuse prevention.</span></label></>:<label>Verification code<input className="otp-input" autoFocus inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000" required/></label>}<button className="auth-primary" disabled={!!busy||(screen==='phone'&&seconds>0)}>{busy?<LoaderCircle className="spin" size={18}/>:null}{screen==='phone'?'Send verification code':'Verify and continue'}<ArrowRight size={17}/></button></form>{screen==='sms'&&<div className="auth-resend"><span>Didn't receive it?</span><button disabled={!!busy||seconds>0} onClick={()=>sendSMS()}>{seconds?`Resend in ${seconds}s`:'Resend code'}</button></div>}</>}
    <div className="auth-captcha" ref={captchaRef}/>
    {screen==='reset'&&<form className="auth-form" onSubmit={e=>{e.preventDefault();perform('reset',async()=>{await sendPasswordResetEmail(requireAuth(),email);setNotice('If an account exists for this email, a reset link will arrive shortly.');});}}><label>Email address<input autoFocus type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><button className="auth-primary" disabled={!!busy}>{busy&&<LoaderCircle className="spin" size={18}/>}Send reset link<ArrowRight size={17}/></button></form>}
    {screen==='verify'&&<div className="auth-form"><button className="auth-primary" disabled={!!busy} onClick={()=>perform('check',async()=>{const current=requireAuth().currentUser;if(!current)throw new Error('Please sign in again.');await current.reload();await current.getIdToken(true);if(!current.emailVerified)throw new Error('Your email is not verified yet. Open the link in your email, then try again.');onSuccess();})}>{busy==='check'?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>}I've verified my email</button><div className="auth-resend"><button disabled={seconds>0||!!busy} onClick={()=>perform('resend',async()=>{await sendEmailVerification(requireAuth().currentUser!);setSeconds(60);setNotice('A fresh verification link is on its way.');})}>{seconds?`Resend in ${seconds}s`:'Resend verification email'}</button></div><button className="auth-forgot" onClick={()=>perform('signout',async()=>{await signOut(requireAuth());route('choices');})}>Use a different account</button></div>}
    {error&&<div role="alert" className="auth-message error">{error}</div>}{notice&&<div role="status" className="auth-message success">{notice}</div>}
    {!config?.auth&&<p className="auth-unavailable">Sign-in is being connected. <a href="/sample">Explore the sample workspace <ArrowRight size={12}/></a></p>}
    <div className="auth-bottom"><span><ShieldCheck size={13}/>Secure sign-in</span><p>By continuing, you agree to our <a href="/terms" target="_blank" rel="noreferrer">Terms</a> and <a href="/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>.</p></div>
  </div>;
}
