import React,{useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronDown,FileText,GitBranch,LockKeyhole,MessageSquare,Plus,ShieldCheck,Sparkles,Zap} from 'lucide-react';
import {readDraft,saveDraft} from './api';
export {Brand as Logo} from './Brand';
import {Brand as Logo} from './Brand';
const examples=[{name:'Beauty & wellness',text:'I run a hair salon in Kuala Lumpur. Help visitors understand our services, ask about their preferred appointment time, and collect their contact details. Answer in English and Bahasa Melayu.'},{name:'Home services',text:'I run a home cleaning business. Ask about the property type, location, number of rooms, and preferred cleaning date. Collect a qualified enquiry for our team to confirm a quote.'},{name:'Education',text:'I run a tuition centre. Explain our subjects, ask about the student age and learning goals, and collect a parent contact number for our team to arrange a consultation.'}];
const faqs=[['What can I build with Lumo?','A conversation plan and a private AI assistant to test it. Add your business knowledge, generate a plan, refine its questions and rules, then approve a version before testing.'],['When will my card be charged?','The seven-day trial costs RM0 today. Unless cancelled before the end, it renews automatically at RM99/month. Your exact first billing date is shown at checkout and in Usage & Billing.'],['What happens when I reach a limit?','AI requests stop at the first reached generation, reply, or AI budget limit. The trial includes 3 plan generations, 50 test replies, and a US$0.50 AI budget. Paid months include 30 generations, 500 replies, and US$5. No automatic overage charges.'],['Can I put the bot on my website or WhatsApp?','This release is for private planning and testing. Website publishing, embeds, and external messaging integrations are not included yet.'],['Can I cancel and keep my work?','You can stop renewal from Usage & Billing. Access continues until the end of your trial or paid period. Afterwards, your saved plans stay readable and editable, but new AI generation and test replies are locked.']];
export function Landing({onStart,signedIn}:{onStart:()=>void;signedIn:boolean}){
  const [prompt,setPrompt]=useState(readDraft);const [selected,setSelected]=useState('');const [faq,setFaq]=useState<number|null>(0);
  const update=(v:string)=>{setPrompt(v);saveDraft(v);};
  return <>
    <header className="site-nav"><div className="nav-inner"><Logo/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a></nav><div className="nav-actions"><button className="text-button login" onClick={onStart}>{signedIn?'My workspace':'Log in'}</button><button className="button primary small" onClick={onStart}>Start free trial <ArrowUpRight size={16}/></button></div></div></header>
    <main>
      <section className="hero">
        <div className="eyebrow"><span className="status-dot"/> A little clarity. A better conversation.</div>
        <h1>Lumo. Your business,<br/><span>ready to answer.</span></h1>
        <p className="hero-description">Turn what you know about your business into an AI conversation.<br className="desktop-break"/> Describe it. Shape the plan. See how it responds.</p>
        <div className="composer-wrap"><form className="composer" onSubmit={e=>{e.preventDefault();onStart();}}>
          <div className="composer-label"><Sparkles size={17}/><label htmlFor="business-prompt">What would you like your assistant to do?</label><span>Start with an idea</span></div>
          <textarea id="business-prompt" maxLength={3000} value={prompt} onChange={e=>update(e.target.value)} placeholder="I run a business that... I'd like my assistant to answer questions, understand what customers need, and..."/>
          <div className="composer-footer"><span><LockKeyhole size={14}/>Your idea stays private</span><button type="submit" className="button primary">Build my plan <ArrowRight size={17}/></button></div>
        </form><div className="prompt-examples"><span>A little inspiration:</span>{examples.map(x=><button key={x.name} onClick={()=>{update(x.text);setSelected(x.name);}} className={selected===x.name?'active':''}><Plus size={13}/>{x.name}</button>)}</div></div>
        <div className="hero-trust"><span><Check size={14}/>7 days free</span><span><Check size={14}/>Then RM99/month</span><span><ShieldCheck size={14}/>Card required. Cancel anytime.</span></div>
        <a className="sample-link" href="/sample">Just looking? Explore a sample workspace <ArrowUpRight size={15}/></a>
      </section>
      <section id="how-it-works" className="workflow section"><div className="section-heading"><div><span className="overline">FROM YOUR IDEA TO YOUR ASSISTANT</span><h2>You know your business.<br/>Give it a voice.</h2></div><p>No blank flowcharts. No complicated setup.<br/>A clear plan you can review before a single test.</p></div>
        <div className="steps"><article><span className="step-icon"><FileText size={21}/></span><span className="step-number">01</span><h3>Tell Lumo what matters</h3><p>Add your services, FAQs, and the things your customers ask every day.</p></article><article><span className="step-icon mint"><GitBranch size={21}/></span><span className="step-number">02</span><h3>Make the plan yours</h3><p>Review the questions, set the boundaries, and approve the conversation.</p></article><article><span className="step-icon pink"><MessageSquare size={21}/></span><span className="step-number">03</span><h3>Try the conversation</h3><p>Step into your customer's shoes. Test, refine, and keep every version.</p></article></div>
      </section>
      <section className="product-band"><div className="section product-inner"><div><span className="overline">YOUR RULES. YOUR VOICE.</span><h2>An assistant with<br/>a plan behind it.</h2><p>Decide what it asks, what it knows, and when it should leave the answer to you.</p><a href="/sample" className="button secondary">Open sample workspace <ArrowUpRight size={16}/></a><small>Fixed example. No account or AI credits needed.</small></div><div className="flow-preview" aria-label="Sample conversation plan"><div className="preview-top"><span><span className="tiny-avatar">B</span> Studio Bloom</span><span className="badge green">Sample plan</span></div>{[{icon:MessageSquare,title:'Welcome the customer',detail:'A friendly greeting, in your own voice.'},{icon:GitBranch,title:'Understand what they need',detail:'Service, preferred date, and contact details.'},{icon:ShieldCheck,title:'Know when to hand over',detail:'Never promise an unconfirmed appointment.'}].map((x,i)=><React.Fragment key={x.title}>{i>0&&<div className="flow-line"/>}<div className="flow-node"><span><x.icon size={17}/></span><div><strong>{x.title}</strong><p>{x.detail}</p></div><Check size={15}/></div></React.Fragment>)}</div></div></section>
      <section id="pricing" className="section pricing-section"><div className="pricing-intro"><span className="overline">ONE SIMPLE PLAN</span><h2>A small start.<br/>Room to get it right.</h2><p>One workspace for your business knowledge, conversation plans, and private testing.</p><div className="pricing-note"><ShieldCheck size={20}/><div><strong>You're in control of the spend.</strong><p>Clear limits. No automatic overage charges.<br/>Cancel renewal in your workspace anytime.</p></div></div></div><div className="price-card"><div className="price-top"><span className="overline">LUMO STARTER</span><span className="badge">7-day free trial</span></div><div className="price">RM99<span>/ month</span></div><p>For a business ready to shape its first assistant.</p><ul>{['1 private AI assistant','30 plan generations or revisions / month','500 private test replies / month','Business knowledge and editable FAQs','Version history and plan approval'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><button className="button primary full" onClick={onStart}>Start my seven-day trial <ArrowRight size={16}/></button><p className="fine">RM0 today, then RM99/month. Card required.<br/>Trial: 3 generations, 50 replies, US$0.50 AI budget.<br/>Paid: US$5 AI budget/month. First reached limit applies.</p></div></section>
      <section id="faq" className="section faq-section"><div><span className="overline">GOOD QUESTIONS</span><h2>A few things<br/>worth knowing.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}<ChevronDown size={18} className={faq===i?'rotate':''}/></button>{faq===i&&<p id={`faq-${i}`}>{a}</p>}</div>)}</div></section>
    </main><footer className="site-footer"><Logo/><span>Better conversations begin with your business.</span><div><a href="/terms">Terms</a><a href="/privacy">Privacy</a><span>&copy; {new Date().getFullYear()} Lumo</span></div></footer>
  </>;
}
