import {Scissors,House,ShoppingBag} from 'lucide-react';
import {salesDemoReply} from './demo-conversation';

export const businesses=[
  {id:'salon',label:'Service sales',name:'Studio Bloom',category:'BEAUTY & PERSONAL SERVICES',icon:Scissors,color:'sage',image:'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=85',alt:'A bright hair salon with styling chairs and mirrors',headline:'Help the right customer choose your service.',description:'Explain the offer, understand the result they want, and guide them to a quote or consultation. Appointments are one next step.',prompt:'I run a hair studio in Kuala Lumpur. Build a sales agent that answers from my services and FAQs, qualifies what customers need, handles price questions using approved facts and asks permission to collect contact details. Suggest a consultation or appointment only when relevant. Match English, Bahasa Melayu, Chinese or a natural mix. Never invent prices or confirm unchecked availability.',greeting:'Hi, welcome to Studio Bloom! Nak explore service apa? English, BM 或中文都可以。',questions:['How much is a haircut?','Mahal, ada pilihan lain?','I want a quote'],fact:'Haircuts from RM65. Tuesday to Sunday, 10am - 7pm, Malaysia time. Colour quotes and appointments need team confirmation.'},
  {id:'home',label:'Quote enquiries',name:'Fresh Space',category:'HOME & BUSINESS SERVICES',icon:House,color:'sky',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85',alt:'A living room illustrating a home service enquiry',headline:'Turn a vague enquiry into a useful quote request.',description:'Understand the job, location and buying timeline. Help your team pick up the conversation with the details that matter.',prompt:'I sell home cleaning services in Malaysia. Build a sales agent that qualifies the property, job scope, area and buying timeline, then asks permission for contact details for a quote. Explain verified services and handle price concerns without inventing discounts. Match English, Bahasa Melayu, Chinese or a mix. Appointments are optional; the team confirms coverage, quote and availability.',greeting:'Hi from Fresh Space! What would you like help with? BM、English 或中文都可以。',questions:['Do you cover Kuala Lumpur?','Berapa harga servis?','I want a quote'],fact:'Serving Kuala Lumpur. Quotes depend on the property and scope. Coverage and prices need team confirmation.'},
  {id:'shop',label:'Product sales',name:'Everyday Studio',category:'RETAIL & PRODUCT ENQUIRIES',icon:ShoppingBag,color:'rose',image:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85',alt:'A retail shop displaying products for customer enquiries',headline:'Help buyers decide, beyond the first price question.',description:'Understand what they are shopping for, explain approved product facts, and guide them towards a purchase or your sales team.',prompt:'I sell products in Malaysia. Build a sales agent that understands customer needs, budget and purchase timing. Recommend only products in my saved catalogue and answer price, stock, delivery and policy questions from verified records. Handle objections honestly and ask permission to collect contact details. Offer only an approved purchase link or team handoff. Match English, Bahasa Melayu, Chinese or their mix. Never invent an order or payment confirmation.',greeting:'Welcome to Everyday Studio! Looking for something in particular? BM、English 或中文都可以。',questions:['How much is the tote?','贵了，有别的选择吗？','How do I buy?'],fact:'Illustrative canvas tote: RM129. Stock, delivery, discounts and payment details require team confirmation. No checkout is connected.'}
] as const;

export function demoReply(id:string,message:string,previous=''){
  return salesDemoReply(id,message,'Malaysian mix',previous);
}
