import {Scissors,House,CalendarDays} from 'lucide-react';
import {appointmentDemoReply} from './demo-conversation';

export const businesses=[
  {id:'salon',label:'Studio appointments',name:'Studio Bloom',category:'IN-STUDIO SERVICES',icon:Scissors,color:'sage',image:'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=85',alt:'A bright hair salon with styling chairs and mirrors',headline:'From a quick question to an appointment request.',description:'Match the customer\'s language, explain your services, and collect their preferred slot for your team to confirm.',prompt:'I run an appointment-based studio in Kuala Lumpur. Answer from my services and FAQs, and collect appointment requests one question at a time. Match English, Bahasa Melayu, Chinese or the customer\'s natural mix. Use RM and Malaysia time. My team confirms prices and availability.',greeting:'Hi, welcome to Studio Bloom! Nak tanya service or appointment? English, BM 或中文都可以。',questions:['How much is a haircut?','Boleh book Sabtu petang?','请问可以预约吗？'],fact:'Haircuts from RM65. Tuesday to Sunday, 10am - 7pm, Malaysia time. The team confirms appointments.'},
  {id:'home',label:'On-site visits',name:'Fresh Space',category:'AT YOUR CUSTOMER\'S LOCATION',icon:House,color:'sky',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85',alt:'A living room prepared for a home service visit',headline:'The right details. Before the visit.',description:'Collect the area, scope and preferred time, without promising a quote or a slot your team has not checked.',prompt:'I run an appointment-based home service in Malaysia. Ask what the customer needs, their area or postcode, and preferred date and time. Reply in their English, BM, Chinese or natural mix. Our team confirms the scope, RM quote, coverage and appointment before a visit.',greeting:'Hi from Fresh Space! Nak arrange a home visit? English, BM 或中文都可以。',questions:['Do you cover Kuala Lumpur?','Berapa harga servis?','明天有 slot 吗？'],fact:'Serving Kuala Lumpur. Quotes depend on the property and scope. The team confirms every visit.'},
  {id:'shop',label:'Consultations',name:'Everyday Studio',category:'MEETINGS & CONSULTATIONS',icon:CalendarDays,color:'rose',image:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=85',alt:'A showroom where customers can arrange an in-person consultation',headline:'A better first conversation. In any industry.',description:'Showroom visits, consultations or one-to-one sessions. Start with what the customer needs, not an industry template.',prompt:'I offer consultations by appointment in Malaysia. Ask the purpose of the visit, preferred date, time and contact details. Reply naturally in English, Bahasa Melayu, Chinese or a mix. Use only my business facts. Ask a person to confirm fees and availability before accepting a booking.',greeting:'Welcome to Everyday Studio! 想了解咨询或预约？English and BM pun boleh.',questions:['Can I request a consultation?','Nak tukar appointment','咨询需要收费吗？'],fact:'Consultation fees, opening hours and availability require team confirmation. This demo cannot make or change appointments.'}
] as const;

export function demoReply(id:string,message:string,previous=''){
  return appointmentDemoReply(id,message,'Malaysian mix',previous);
}
