import React,{useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,GitBranch,LockKeyhole,Menu,MessageSquare,Moon,Plus,RotateCcw,ShieldCheck,Sparkles,Sun,X} from 'lucide-react';
import {Brand,BrandMark} from './Brand';
import {readDraft,saveDraft} from './api';
import {businesses,demoReply} from './landing-data';
import './lumo.css';

const steps=[
  {name:'Tell it your business',title:<>Your knowledge.<br/>Its starting point.</>,description:'Your services, prices, FAQs, and the little things that make your business yours. Give Lumo the facts you want every conversation to start with.',icon:BookOpen,label:'Business knowledge'},
  {name:'Shape the conversation',title:<>A clear plan.<br/>With you in control.</>,description:'Review the greeting, questions, and next steps. Set the rules. Make it sound like you. Every change becomes a version you can return to.',icon:GitBranch,label:'Conversation plan'},
  {name:'Try it for yourself',title:<>Your next chatbot.<br/>Ready for a rehearsal.</>,description:'Ask what your customers would ask. See how your approved plan responds, refine the details, and find the right moment for a human handoff.',icon:MessageSquare,label:'Test chat'}
];
const faqs=[
  ['What can I build with Lumo?','An AI chatbot conversation plan for your business, with your knowledge, FAQs, questions, and handoff rules. The first release includes private planning, editing, version history, and test conversations.'],
  ['Do I need to know how to code?','No. Start with a plain-language description of your business and the conversation you want. You can edit the generated greeting, questions, rules, and lead fields before approving a plan.'],
  ['Can I try it before creating an account?','Yes. The interactive demo uses preset examples and replies, so you can explore without an account, a card, or any AI credits. Your own business brief is saved on this device.'],
  ['How does the seven-day trial work?','At launch, eligible businesses can start a seven-day trial with a supported credit or debit card. You pay RM0 at the start, then RM99/month unless you cancel renewal before the trial ends. The exact first billing date will appear at checkout. Checkout is not active in this preview.'],
  ['What are the usage limits?','The trial includes up to 3 plan generations, 50 test replies, and a US$0.50 AI budget in total. Each paid month includes up to 30 generations, 500 replies, and a US$5 AI budget. AI stops at the first limit reached. There are no automatic overage charges.'],
  ['Can I add it to my website or WhatsApp?','Website embeds, publishing, and WhatsApp automation are planned for a later release. The current experience focuses on building, reviewing, and testing your chatbot privately.'],
  ['Can I cancel and keep my work?','Yes. Once billing is connected, you can cancel renewal from your workspace. Access continues until the end of your trial or paid period. Your saved plans remain available afterwards; new AI calls require an active subscription.']
];

function WorkspacePreview({stage,small=false}:{stage:number;small?:boolean}){
  return <div className={`lp-workspace-preview ${small?'is-small':''}`}>
    <div className="lp-preview-chrome"><span><BrandMark/>lumo</span><span><LockKeyhole size={12}/>Studio Bloom</span><span className="lp-avatar">B</span></div>
    <div className="lp-preview-tabs">{steps.map((step,i)=><span className={stage===i?'active':''} key={step.label}><step.icon size={14}/>{['Knowledge','Plan','Test'][i]}</span>)}</div>
    <div className="lp-preview-body" key={stage}><div className="lp-preview-heading"><span>STUDIO BLOOM</span><span className="lp-small-status">{stage===0?'Saved':stage===1?'Approved':'Private test'}</span></div><h3>{['The facts behind every answer.','A better conversation starts here.','A little hello goes a long way.'][stage]}</h3>
      {stage===0?<div className="lp-knowledge-rows"><div><BookOpen size={17}/><div><strong>About the business</strong><p>A neighbourhood hair salon in Kuala Lumpur.</p></div><Check size={14}/></div><div><MessageSquare size={17}/><div><strong>Services & frequently asked questions</strong><p>Haircuts from RM65. Colour by consultation.<br/>Tuesday to Sunday, 10am - 7pm.</p></div><Check size={14}/></div><div><ShieldCheck size={17}/><div><strong>A little guidance</strong><p>Our team confirms every appointment.<br/>Never promise an unchecked time.</p></div><Check size={14}/></div></div>:stage===1?<div className="lp-plan-nodes">{[{title:'Welcome the customer',text:'A warm greeting, in your own voice.',icon:MessageSquare},{title:'Understand what they need',text:'Service, preferred date, and contact details.',icon:GitBranch},{title:'Pass it to the right person',text:'Your team confirms the final appointment.',icon:ShieldCheck}].map((item,i)=><div key={item.title}><span className={`lp-node-icon node-${i}`}><item.icon size={17}/></span><div><span>0{i+1}</span><strong>{item.title}</strong><p>{item.text}</p></div><Check size={14}/></div>)}<p className="lp-approval-note"><CheckCheck size={14}/>Reviewed by you. Ready to test.</p></div>:<div className="lp-preview-chat"><div className="lp-chat-user">Hi! How much is a haircut?</div><div className="lp-chat-bot"><BrandMark/><p>Hi there! Our haircuts start from RM65. What style do you have in mind?</p></div><div className="lp-chat-user">A trim, next Saturday.</div><div className="lp-chat-bot"><BrandMark/><p>Lovely. What time would you prefer? Our team will confirm availability with you.</p></div></div>}
    </div><div className="lp-preview-bottom"><span className="lp-indicator"/>Illustrative workspace<span>Made with lumo</span></div>
  </div>;
}

function ProductFan({onDemo}:{onDemo:()=>void}){
  return <div className="lp-product-fan" aria-label="Lumo workspace examples">
    <button className="lp-fan-card lp-fan-left" onClick={onDemo} aria-label="Explore the Studio Bloom chatbot demo"><div className="lp-fan-photo"><img src={businesses[0].image} alt="Studio Bloom salon example"/><span><ScissorsLabel/>Studio Bloom</span></div><div className="lp-fan-content"><span className="lp-mini-label">YOUR BUSINESS, REMEMBERED</span><h3>A good answer starts<br/>with what you know.</h3><div><BookOpen size={15}/><span>Services, prices & FAQs</span><Check size={14}/></div><div><ShieldCheck size={15}/><span>Your rules & boundaries</span><Check size={14}/></div></div></button>
    <button className="lp-fan-card lp-fan-center" onClick={onDemo} aria-label="Explore a sample Lumo conversation plan"><div className="lp-fan-center-top"><BrandMark/><span>One idea.<br/><strong>A conversation that fits.</strong></span></div><div className="lp-fan-flow"><div><MessageSquare size={16}/><span>Start with a hello</span><Check size={13}/></div><i/><div><GitBranch size={16}/><span>Ask the right questions</span><Check size={13}/></div><i/><div><ArrowUpRight size={16}/><span>Find the next step</span><Check size={13}/></div></div><span className="lp-fan-footer"><CheckCheck size={14}/>Your plan. Your approval.</span></button>
    <button className="lp-fan-card lp-fan-right" onClick={onDemo} aria-label="Try a sample chatbot conversation"><div className="lp-fan-chat-head"><span><BrandMark/></span><div><strong>Studio Bloom assistant</strong><small>A sample conversation</small></div><span className="lp-online"/></div><div className="lp-fan-chat"><p className="from-visitor">Hi, do you have any appointments on Saturday?</p><p className="from-lumo">Hi! Which service are you thinking of? I can take your preferred time for our team to confirm.</p><p className="from-visitor">A haircut, around 11?</p><p className="from-lumo">Of course. What name should we put with your enquiry?</p></div><span className="lp-fan-chat-input">Every hello, a little easier.<ArrowUpRight size={15}/></span></button>
  </div>;
}
function ScissorsLabel(){const Icon=businesses[0].icon;return <Icon size={15}/>;}

function Playground(){
  const [industry,setIndustry]=useState(0);const [messages,setMessages]=useState<{role:'user'|'bot';text:string}[]>([]);const [message,setMessage]=useState('');const [typing,setTyping]=useState(false);
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const scroll=useRef<HTMLDivElement>(null);const business=businesses[industry];
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
  useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;},[messages,typing]);
  function reset(index=industry){if(timer.current)clearTimeout(timer.current);setIndustry(index);setMessages([]);setMessage('');setTyping(false);}
  function send(text=message){if(!text.trim()||typing||messages.length>=16)return;setMessages(m=>[...m,{role:'user',text:text.trim()}]);setMessage('');setTyping(true);timer.current=setTimeout(()=>{setMessages(m=>[...m,{role:'bot',text:demoReply(business.id,text)}]);setTyping(false);},650);}
  return <section className="lp-playground" id="playground"><div className="lp-container lp-playground-grid"><div className="lp-demo-copy" data-enter><span className="lp-eyebrow light">A LITTLE LESS TELL. A LITTLE MORE SHOW.</span><h2>Go on.<br/>Say hello.</h2><p>Be the customer for a moment.<br/>See how a thoughtful conversation feels.</p><div className="lp-demo-businesses" role="group" aria-label="Demo business">{businesses.map((b,i)=><button key={b.id} aria-pressed={industry===i} className={industry===i?'active':''} onClick={()=>reset(i)}><b.icon size={19}/><span>{b.label}</span><ArrowUpRight size={17}/></button>)}</div><p className="lp-demo-note"><LockKeyhole size={14}/>Preset demo. No account, card, or AI credits.</p></div><div className="lp-demo-chat" data-enter><div className="lp-demo-head"><div className={`lp-demo-avatar ${business.color}`}><business.icon size={21}/></div><div><strong>{business.name}</strong><span><span className="lp-indicator"/>Lumo sample assistant</span></div><button className="lp-icon-button" title="Restart demo conversation" aria-label="Restart demo conversation" onClick={()=>reset()}><RotateCcw size={17}/></button></div><div className="lp-demo-messages" ref={scroll} role="log" aria-label="Sample conversation" aria-live="polite"><div className="lp-demo-date">YOUR PRIVATE REHEARSAL</div><div className="lp-demo-message bot"><BrandMark/><p>{business.greeting}</p></div>{messages.map((m,i)=><div key={i} className={`lp-demo-message ${m.role}`}>{m.role==='bot'&&<BrandMark/>}<p>{m.text}</p></div>)}{typing&&<div className="lp-demo-message bot"><BrandMark/><p className="lp-typing" aria-label="Preparing sample reply"><span/><span/><span/></p></div>}</div><div className="lp-demo-suggestions">{business.questions.map(q=><button key={q} disabled={typing||messages.length>=16} onClick={()=>send(q)}>{q}<ArrowUpRight size={12}/></button>)}</div><form className="lp-demo-form" onSubmit={e=>{e.preventDefault();send();}}><input aria-label="Message the sample chatbot" value={message} maxLength={500} onChange={e=>setMessage(e.target.value)} placeholder={messages.length>=16?'Restart to try another conversation':'Ask a question...'} disabled={typing||messages.length>=16}/><button disabled={!message.trim()||typing||messages.length>=16} title="Send sample message" aria-label="Send sample message"><ArrowUpRight size={21}/></button></form><div className="lp-demo-disclosure">Illustrative replies. No real bookings or messages are sent.</div></div></div></section>;
}

export function LumoLanding({onStart,onLogin,signedIn,theme,onTheme}:{onStart:()=>void;onLogin:()=>void;signedIn:boolean;theme:'dark'|'light';onTheme:()=>void}){
  const [prompt,setPrompt]=useState(readDraft);const [selected,setSelected]=useState<number|null>(null);const [menu,setMenu]=useState(false);const [stage,setStage]=useState(0);const [faq,setFaq]=useState<number|null>(0);
  const root=useRef<HTMLDivElement>(null);const showcase=useRef<HTMLDivElement>(null);const statement=useRef<HTMLElement>(null);const scrollBar=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    const page=root.current!;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('entered');observer.unobserve(entry.target);}}),{threshold:.08});page.querySelectorAll('[data-enter]').forEach(el=>observer.observe(el));
    const chapterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setStage(Number((entry.target as HTMLElement).dataset.step));}),{rootMargin:'-30% 0px -40% 0px',threshold:0});page.querySelectorAll('[data-step]').forEach(el=>chapterObserver.observe(el));
    let frame=0;
    function update(){if(frame)return;frame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;if(scrollBar.current)scrollBar.current.style.transform=`scaleX(${max>0?scrollY/max:0})`;if(!reduced.matches){if(showcase.current){const p=Math.max(0,Math.min(1,(innerHeight-showcase.current.getBoundingClientRect().top)/(innerHeight*.85)));showcase.current.style.setProperty('--fan-progress',String(p));}if(statement.current){const rect=statement.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,(innerHeight*.82-rect.top)/(innerHeight*.65)));statement.current.querySelectorAll<HTMLElement>('[data-word]').forEach((word,i,words)=>{word.style.opacity=String(i/words.length<p?1:.2);});}}frame=0;});}
    window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();return()=>{observer.disconnect();chapterObserver.disconnect();window.removeEventListener('scroll',update);window.removeEventListener('resize',update);cancelAnimationFrame(frame);};
  },[]);
  useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape')setMenu(false);}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
  function updatePrompt(text:string){setPrompt(text);saveDraft(text);}
  function useExample(index:number,scrollToTop=false){setSelected(index);updatePrompt(businesses[index].prompt);if(scrollToTop){document.getElementById('builder')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});document.getElementById('business-idea')?.focus({preventScroll:true});}}
  function openDemo(){document.getElementById('playground')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
  function begin(){document.getElementById('builder')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});document.getElementById('business-idea')?.focus({preventScroll:true});}
  return <div className="lumo-site" ref={root}><a className="lp-skip" href="#business-idea">Skip to chatbot builder</a><div className="lp-reading-progress" ref={scrollBar}/>
    <header className="lp-header"><div className="lp-nav-inner"><Brand/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#use-cases">Who it's for</a><a href="#pricing">Pricing</a></nav><div className="lp-nav-actions"><button className="lp-theme" title={`Switch to ${theme==='light'?'dark':'light'} mode`} aria-label={`Switch to ${theme==='light'?'dark':'light'} mode`} onClick={onTheme}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button className="lp-login" onClick={onLogin}>{signedIn?'My workspace':'Log in'}</button><button className="lp-button lp-button-dark nav-start" onClick={begin}>Start building<ArrowUpRight size={16}/></button><button className="lp-menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="lp-mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></div>{menu&&<nav className="lp-mobile-nav" id="lp-mobile-nav" aria-label="Mobile navigation">{[['How it works','#how-it-works'],["Who it's for",'#use-cases'],['Try the demo','#playground'],['Pricing','#pricing']].map(([title,href])=><a href={href} key={href} onClick={()=>setMenu(false)}>{title}<ArrowUpRight size={16}/></a>)}<button onClick={()=>{setMenu(false);onLogin();}}>{signedIn?'My workspace':'Log in'}<ArrowRight size={16}/></button></nav>}</header>
    <main>
      <section className="lp-hero" id="hero"><div className="lp-hero-content"><span className="lp-hero-eyebrow"><BrandMark/>YOUR BUSINESS, IN CONVERSATION</span><h1>AI chatbots.<br/><span>Built around you.</span></h1><p className="lp-hero-description">Turn your business knowledge into better answers.<br/>Describe it. Shape the conversation. Meet your chatbot.</p><form className="lp-prompt" id="builder" onSubmit={e=>{e.preventDefault();saveDraft(prompt);onStart();}}><label htmlFor="business-idea" className="lp-sr-only">Describe your business and what your chatbot should do</label><textarea id="business-idea" rows={2} value={prompt} onChange={e=>updatePrompt(e.target.value)} placeholder="I run a business that... I'd like a chatbot to..." maxLength={3000} minLength={10} required/><div className="lp-prompt-actions"><span><Sparkles size={16}/>Your idea starts here</span><button className="lp-button lp-button-dark" type="submit">Create my chatbot<ArrowUpRight size={18}/></button></div></form><div className="lp-prompt-examples"><span>Try an idea</span>{businesses.map((b,i)=><button type="button" key={b.id} onClick={()=>useExample(i)} aria-pressed={selected===i}><b.icon size={14}/>{b.label}</button>)}</div><div className="lp-hero-proof"><span><Check size={13}/>No code needed</span><span><Check size={13}/>You approve every plan</span><a href="#playground">Try a sample first<ArrowUpRight size={13}/></a></div></div></section>
      <div className="lp-showcase" ref={showcase}><ProductFan onDemo={openDemo}/><div className="lp-showcase-caption"><span>YOUR KNOWLEDGE</span><span>YOUR CONVERSATION</span><span>YOUR CHATBOT</span></div></div>
      <section className="lp-statement lp-container" ref={statement}><div className="lp-section-label"><span className="lp-indicator"/>MEET LUMO<span>MORE THAN A QUICK REPLY</span></div><h2>{'You know your business. Lumo helps you turn that knowledge into conversations that move things forward.'.split(' ').map((word,i)=><React.Fragment key={i}><span data-word>{word}</span>{' '}</React.Fragment>)}</h2><div className="lp-statement-bottom"><span className="lp-round-arrow"><ArrowDown size={25} strokeWidth={1.5}/></span><p>From the first question to a thoughtful handoff.<br/>An AI chatbot shaped by you, for the way you do business.</p></div></section>
      <section className="lp-how lp-container" id="how-it-works"><div className="lp-section-label"><span>01 / HOW IT WORKS</span><span>ONE IDEA. THREE SIMPLE STEPS.</span></div><div className="lp-story-grid"><div className="lp-story-chapters">{steps.map((step,i)=><article className={`lp-story-step ${stage===i?'active':''}`} key={step.name} data-step={i} id={`step-${i}`}><span className="lp-step-number">0{i+1}<span>{step.name}</span></span><h2>{step.title}</h2><p>{step.description}</p><a className="lp-text-link" href="/sample">Explore the sample workspace<ArrowUpRight size={16}/></a><div className="lp-step-meter">{steps.map((_,n)=><span className={n<=i?'complete':''} key={n}/>)}</div><div className="lp-mobile-preview"><WorkspacePreview stage={i}/></div></article>)}</div><div className="lp-story-visual"><WorkspacePreview stage={stage}/><div className="lp-story-caption"><span>0{stage+1} / {steps[stage].label}</span><span>Private. Editable. Yours.</span></div></div></div></section>
      <div className="lp-principles"><div className="lp-container lp-principles-grid">{[{icon:BookOpen,title:'Answers with a source.',text:'Your business knowledge is the starting point for every reply.'},{icon:ShieldCheck,title:'Boundaries you decide.',text:'Set what your chatbot can say, ask, and leave to a person.'},{icon:GitBranch,title:'Room to get it right.',text:'Review, edit, and keep every version of your conversation plan.'}].map((item,i)=><article key={item.title} data-enter style={{'--entry-delay':`${i*80}ms`} as React.CSSProperties}><item.icon size={25} strokeWidth={1.4}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div>
      <section className="lp-use-cases lp-container" id="use-cases"><div className="lp-section-label"><span>02 / MADE FOR YOUR BUSINESS</span><span>DIFFERENT BUSINESSES. BETTER CONVERSATIONS.</span></div><div className="lp-section-heading" data-enter><h2>A familiar question.<br/><span>A better way to answer.</span></h2><p>Start with a business like yours.<br/>Then make every detail your own.</p></div><div className="lp-business-grid">{businesses.map((b,i)=><article className={`lp-business-card ${b.color}`} key={b.id} data-enter style={{'--entry-delay':`${i*90}ms`} as React.CSSProperties}><button className="lp-business-image" onClick={()=>useExample(i,true)} aria-label={`Start with the ${b.label.toLowerCase()} example`}><img src={b.image} alt={b.alt} loading="lazy"/><span className="lp-business-photo-label"><b.icon size={15}/>{b.label}</span><span className="lp-business-photo-arrow"><ArrowUpRight size={20}/></span></button><div className="lp-business-description"><span className="lp-eyebrow">{b.category}</span><h3>{b.headline}</h3><p>{b.description}</p><button className="lp-text-link" onClick={()=>useExample(i,true)}>Start with this idea<ArrowUpRight size={15}/></button></div></article>)}</div></section>
      <Playground/>
      <section className="lp-pricing lp-container" id="pricing"><div className="lp-section-label"><span>03 / A SIMPLE START</span><span>CLEAR PRICING. ROOM TO EXPLORE.</span></div><div className="lp-price-grid"><div className="lp-price-intro" data-enter><span className="lp-eyebrow">LUMO STARTER</span><h2>Your first chatbot.<br/><span>Your next chapter.</span></h2><p>One workspace for your business knowledge,<br/>conversation plans, and private testing.</p><div className="lp-launch-note"><span className="lp-indicator"/><span>Explore the preview today.<br/>Subscriptions open when the service launches.</span></div><a href="#playground" className="lp-text-link">Try before you decide<ArrowUpRight size={16}/></a></div><div className="lp-price-offer" data-enter><div className="lp-price-top"><span>THE LAUNCH PLAN</span><span>7-day trial</span></div><div className="lp-amount"><span>RM</span>99<small>/ month</small></div><p>One business. One private AI chatbot.</p><ul>{['30 plan generations or AI revisions each month','500 private test replies each month','Business knowledge and editable FAQs','Plan approval and complete version history'].map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul><button className="lp-button lp-button-dark" onClick={begin}>Start with your business<ArrowUpRight size={18}/></button><div className="lp-price-footnote">At launch: RM0 for 7 days, then RM99/month. Card required. Renews automatically until cancelled.<br/><br/>Trial: 3 generations, 50 replies, US$0.50 AI budget.<br/>Paid: US$5 AI budget/month. The first limit reached applies.<br/>No automatic overage charges.</div></div></div></section>
      <section className="lp-faq lp-container" id="faq"><div className="lp-faq-intro" data-enter><span className="lp-eyebrow">A LITTLE CLARITY</span><h2>Good questions.<br/><span>Honest answers.</span></h2><a className="lp-text-link" href="#playground">See Lumo for yourself<ArrowUpRight size={16}/></a></div><div className="lp-faq-list" data-enter>{faqs.map(([q,a],i)=><div className="lp-faq-item" key={q}><h3><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={`lp-answer-${i}`}><span className="lp-faq-number">0{i+1}</span><span>{q}</span><Plus size={18} className={faq===i?'expanded':''}/></button></h3><div id={`lp-answer-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
      <section className="lp-closing"><div className="lp-container"><BrandMark/><span className="lp-eyebrow">A LITTLE LESS REPETITION. A LOT MORE POSSIBILITY.</span><h2>Your next chatbot<br/>starts with one idea.</h2><button className="lp-button lp-button-dark" onClick={begin}>Let's build yours<ArrowUpRight size={18}/></button><a href="#playground">Or say hello to the demo<ArrowUpRight size={14}/></a></div></section>
    </main><footer className="lp-footer"><div className="lp-container"><div className="lp-footer-top"><Brand/><p>Your business, in conversation.</p><nav aria-label="Footer navigation"><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQs</a></nav></div><div className="lp-footer-wordmark" aria-hidden="true">lumo<span><MessageSquare strokeWidth={1.3}/></span></div><div className="lp-footer-bottom"><span>&copy; {new Date().getFullYear()} Lumo</span><span>Thoughtful chatbots. Better conversations.</span><div><a href="/terms">Terms</a><a href="/privacy">Privacy</a><button onClick={onTheme}>{theme==='light'?<Moon size={13}/>:<Sun size={13}/>} {theme==='light'?'Dark':'Light'} mode</button></div></div></div></footer>
  </div>;
}
