import React,{useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronDown,GitBranch,LockKeyhole,Menu,MessageSquare,Moon,Plus,ShieldCheck,Sparkles,Sun,X} from 'lucide-react';
import {readDraft,saveDraft} from './api';

const examples=[
  {name:'Beauty & wellness',prompt:'I run a hair salon in Kuala Lumpur. Explain our services, ask about the preferred appointment date, and collect contact details for our team to confirm. Answer in English and Bahasa Melayu.'},
  {name:'Home services',prompt:'I run a home cleaning business. Ask about the property type, location, number of rooms, and preferred cleaning date. Collect a qualified enquiry for our team to prepare a quote.'},
  {name:'Education',prompt:'I run a tuition centre. Explain our subjects, ask about the student age and learning goals, and collect a parent contact number for a consultation.'}
];
const chapters=[
  {label:'The knowledge',title:<>Your business.<br/>The whole picture.</>,text:'The details make the difference. Bring your services, FAQs, and business rules together, so every answer starts with what you know.',tag:'01 / KNOW',icon:BookOpen},
  {label:'The conversation',title:<>A little structure.<br/>A lot of possibility.</>,text:'Turn one prompt into a considered conversation. Shape the questions. Set the boundaries. Approve the version that sounds like you.',tag:'02 / SHAPE',icon:GitBranch},
  {label:'The rehearsal',title:<>Meet your assistant.<br/>Before anyone else.</>,text:'Ask the difficult questions. Try a different path. Refine in a private workspace, with every earlier version still there when you need it.',tag:'03 / REFINE',icon:MessageSquare}
];
const faqs=[
  ['What is included in this release?','Your private builder: business knowledge, AI-generated conversation plans, editable version history, plan approval, and a private test chat. Website publishing, embedded bots, and WhatsApp automation are not included yet.'],
  ['How does the seven-day trial work?','Create and verify your account, then add a supported credit or debit card through Stripe. Eligible businesses pay RM0 today, then RM99/month after seven days unless cancelled. The exact first billing date is shown at checkout.'],
  ['What happens when I reach a limit?','New AI calls stop at the first reached generation, reply, or AI budget limit. The trial allows up to 3 generations, 50 replies, and US$0.50 of AI usage. Paid months allow up to 30 generations, 500 replies, and US$5. Longer prompts can reach the budget first. There are no automatic overage charges.'],
  ['Can I cancel and keep my work?','Yes. Cancel renewal in Usage & Billing. You keep access through the end of your trial or paid period. After that, saved plans remain readable and editable. New AI generation and test replies require an active subscription.'],
  ['Can I explore before adding a card?','Absolutely. Describe your business on this page and explore our fixed sample workspace without an account. Your draft is saved on this device. A verified trial or subscription is required before Lumo generates a real plan.']
];

function ProductPreview({stage}:{stage:number}){
  return <div className="cinema-product" aria-label={`Sample workspace: ${chapters[stage].label}`}>
    <div className="product-chrome"><span className="product-wordmark">lumo<span>.</span></span><span><LockKeyhole size={12}/>Private workspace</span><span className="product-avatar">B</span></div>
    <div className="product-tabs">{chapters.map((c,i)=><span key={c.label} className={i===stage?'active':''}><c.icon size={15}/>{['Knowledge','Plan','Test chat'][i]}</span>)}</div>
    <div className="product-stage" key={stage}>
      <div className="product-stage-title"><div><span>STUDIO BLOOM</span><h3>{['A foundation of facts.','Every conversation, considered.','A conversation worth having.'][stage]}</h3></div><span className="sample-indicator">Sample</span></div>
      {stage===0?<div className="sample-knowledge"><div><span>01</span><div><strong>Our business</strong><p>A neighbourhood hair salon in Kuala Lumpur.<br/>Thoughtful cuts. Personal attention.</p></div><Check size={17}/></div><div><span>02</span><div><strong>The details</strong><p>Haircuts from RM65. Tuesday to Sunday, 10am - 7pm.</p></div><Check size={17}/></div><div><span>03</span><div><strong>The boundaries</strong><p>Our team confirms every appointment. Never promise a time that has not been checked.</p></div><ShieldCheck size={17}/></div></div>:stage===1?<div className="sample-flow">{[{title:'Start with a warm welcome',text:'Hello! Welcome to Studio Bloom. What can we help you with?',icon:MessageSquare},{title:'Understand what matters',text:'Service, preferred date, and a way to reach you.',icon:GitBranch},{title:'Leave the final word to your team',text:'Appointment requests are always confirmed by a human.',icon:ShieldCheck}].map((n,i)=><div key={n.title}><div className="sample-flow-rail"><n.icon size={17}/></div><div><span>0{i+1}</span><h4>{n.title}</h4><p>{n.text}</p></div></div>)}<div className="sample-approved"><CheckCheck size={15}/>Plan approved for private testing</div></div>:<div className="sample-chat"><div className="sample-chat-user">Hi! How much is a haircut?</div><div className="sample-chat-bot"><span>L</span><p>Hi there! Our haircuts start from RM65.<br/><br/>Would you like to tell me a little about the style you have in mind?</p></div><div className="sample-chat-user">A trim, next Saturday.</div><div className="sample-chat-bot"><span>L</span><p>Of course. What time would you prefer? Our team will check availability and confirm with you.</p></div></div>}
    </div>
    <div className="product-bottom"><span><span className="live-dot"/>Fixed example. No live AI.</span><a href="/sample">Explore workspace <ArrowUpRight size={14}/></a></div>
  </div>;
}

export function PremiumLanding({onStart,onLogin,signedIn,theme,onTheme}:{onStart:()=>void;onLogin:()=>void;signedIn:boolean;theme:'dark'|'light';onTheme:()=>void}){
  const [prompt,setPrompt]=useState(readDraft);const [stage,setStage]=useState(0);const [faq,setFaq]=useState<number|null>(0);const [menu,setMenu]=useState(false);const [example,setExample]=useState(0);
  const root=useRef<HTMLDivElement>(null);const hero=useRef<HTMLElement>(null);const progress=useRef<HTMLDivElement>(null);
  useEffect(()=>{
    const el=root.current!;const media=matchMedia('(prefers-reduced-motion: reduce)');
    const reveals=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');reveals.unobserve(entry.target);}}),{threshold:.1});
    el.querySelectorAll('[data-reveal]').forEach(node=>reveals.observe(node));
    const story=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setStage(Number((entry.target as HTMLElement).dataset.chapter));}),{rootMargin:'-30% 0px -45% 0px',threshold:0});
    el.querySelectorAll('[data-chapter]').forEach(node=>story.observe(node));
    let frame=0;
    const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{const y=window.scrollY;const total=document.documentElement.scrollHeight-innerHeight;if(progress.current)progress.current.style.transform=`scaleX(${total>0?y/total:0})`;if(hero.current&&!media.matches)hero.current.style.setProperty('--hero-shift',`${Math.min(y*.13,100)}px`);frame=0;});};
    window.addEventListener('scroll',scroll,{passive:true});scroll();
    return()=>{reveals.disconnect();story.disconnect();window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};
  },[]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  function update(text:string){setPrompt(text);saveDraft(text);}
  function choose(i:number){setExample(i);update(examples[i].prompt);document.getElementById('lumo-prompt')?.focus();}
  return <div className="premium-page" ref={root}>
    <a className="skip-link" href="#lumo-prompt">Skip to builder</a><div className="reading-progress" ref={progress}/>
    <header className="premium-nav"><a className="premium-logo" href="/" aria-label="Lumo home">lumo<span>.</span></a><nav aria-label="Main navigation"><a href="#experience">The experience</a><a href="#possibilities">Made for you</a><a href="#pricing">Pricing</a></nav><div className="premium-nav-actions"><button className="theme-toggle" onClick={onTheme} title={`Switch to ${theme==='dark'?'light':'dark'} mode`} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><button className="premium-login" onClick={onLogin}>{signedIn?'Workspace':'Log in'}</button><button className="premium-cta nav-cta" onClick={onStart}>Get started <ArrowUpRight size={16}/></button><button className="mobile-menu-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(!menu)}>{menu?<X size={21}/>:<Menu size={21}/>}</button></div></header>
    {menu&&<nav id="mobile-navigation" className="mobile-navigation" aria-label="Mobile navigation">{[['The experience','#experience'],['Made for you','#possibilities'],['Pricing','#pricing'],['Questions','#faq']].map(([title,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{title}<ArrowUpRight size={19}/></a>)}<button onClick={()=>{setMenu(false);onLogin();}}>{signedIn?'My workspace':'Log in'}<ArrowRight size={19}/></button></nav>}
    <main>
      <section className="cinema-hero" ref={hero}>
        <img className="hero-art" src="/lumo-cinematic.png" alt="Sculptural Lumo L in brushed silver and clear glass" fetchPriority="high"/>
        <div className="hero-main"><div className="hero-kicker"><span className="live-dot"/>YOUR BUSINESS. A NEW VOICE.</div><h1>Lumo<span>.</span></h1><h2>Make every hello<br/>mean business.</h2><p className="cinema-description">From one idea to your own AI assistant.<br/>Thoughtfully planned. Entirely yours.</p>
          <form className="cinema-composer" onSubmit={e=>{e.preventDefault();onStart();}}><label htmlFor="lumo-prompt"><Sparkles size={16}/>What should your assistant do?</label><textarea id="lumo-prompt" value={prompt} onChange={e=>update(e.target.value)} maxLength={3000} placeholder="I run a business that..." rows={2}/><div><span><LockKeyhole size={12}/>Your draft stays on this device</span><button type="submit" className="premium-cta">Generate plan <ArrowUpRight size={17}/></button></div></form>
          <div className="hero-under"><span>7 days free. Then RM99/month.</span><a href="/sample">Explore the sample <ArrowUpRight size={13}/></a></div>
        </div><div className="hero-side-note"><span>BUILT AROUND YOU</span><p>Your knowledge.<br/>Your rules.<br/>Your next chapter.</p></div>
        <div className="hero-bottom"><a href="#experience">Discover Lumo <ArrowDown size={15}/></a><span>Private planning & testing<span className="hero-bottom-line"/>01 / 03</span></div>
      </section>
      <section className="cinema-intro premium-section" id="experience"><div className="section-meta" data-reveal><span>01 / THE EXPERIENCE</span><span>LESS FRICTION. MORE INTENTION.</span></div><h2 data-reveal>It starts with your idea.<br/><span>It becomes your voice.</span></h2><div className="intro-bottom" data-reveal><span className="intro-symbol"><ArrowDown size={28} strokeWidth={1}/></span><p>Not just answers. The right conversation.<br/>A space to bring your business knowledge, your voice, and your next assistant together.</p></div></section>
      <section className="cinema-story premium-section" aria-label="How Lumo works"><div className="story-copy">{chapters.map((c,i)=><article className={`story-chapter ${stage===i?'active':''}`} key={c.label} data-chapter={i}><span className="chapter-label"><span>0{i+1}</span>{c.label}</span><h2>{c.title}</h2><p>{c.text}</p><a href="/sample" className="premium-text-link">See it in the workspace <ArrowUpRight size={17}/></a><div className="chapter-progress">{chapters.map((_,n)=><span className={n<=i?'filled':''} key={n}/>)}</div><div className="mobile-product"><ProductPreview stage={i}/></div></article>)}</div><div className="story-visual"><ProductPreview stage={stage}/><div className="story-visual-caption"><span>{chapters[stage].tag}</span><span>Your thinking, with a little more structure.</span></div></div></section>
      <section className="principles-band"><div className="premium-section principles-inner">{[{icon:ShieldCheck,title:'Your approval. Always.',text:'Every plan is yours to review before a test begins.'},{icon:GitBranch,title:'Room to change your mind.',text:'New ideas become new versions. Nothing gets lost.'},{icon:LockKeyhole,title:'A private place to begin.',text:'Only your workspace. No public bots or messages.'}].map((x,i)=><article data-reveal key={x.title} style={{'--reveal-delay':`${i*90}ms`} as React.CSSProperties}><x.icon size={23} strokeWidth={1.4}/><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
      <section className="possibilities premium-section" id="possibilities"><div className="section-meta" data-reveal><span>02 / MADE FOR YOU</span><span>YOUR AMBITION. YOUR STARTING POINT.</span></div><div className="possibilities-heading" data-reveal><h2>Every business has<br/><span>a conversation to start.</span></h2><p>For the questions you hear every day.<br/>And the opportunities in every answer.</p></div><div className="industry-examples" data-reveal><div className="industry-list" role="tablist" aria-label="Business examples">{examples.map((x,i)=><button id={`industry-${i}`} role="tab" aria-selected={example===i} aria-controls="industry-panel" key={x.name} onClick={()=>setExample(i)} className={example===i?'selected':''}><span>0{i+1}</span>{x.name}<ArrowUpRight size={22}/></button>)}</div><div id="industry-panel" className="industry-detail" role="tabpanel" aria-labelledby={`industry-${example}`} key={example}><span className="small-caps">A STARTING POINT</span><p>&ldquo;{examples[example].prompt}&rdquo;</p><a href="#lumo-prompt" className="premium-text-link" onClick={()=>choose(example)}>Make this idea yours <ArrowUpRight size={17}/></a></div></div></section>
      <section id="pricing" className="cinema-pricing"><div className="premium-section"><div className="section-meta" data-reveal><span>03 / YOUR NEXT CHAPTER</span><span>A SIMPLE PLAN. A CLEAR START.</span></div><div className="premium-price-grid"><div className="price-editorial" data-reveal><h2>Big possibilities.<br/><span>One simple plan.</span></h2><p>A little space to explore.<br/>Everything you need to shape your first assistant.</p><div className="price-assurance"><ShieldCheck size={22}/><span>Clear limits. No automatic overages.<br/>Your next step is always your choice.</span></div></div><div className="premium-price" data-reveal><div className="premium-price-top"><span>LUMO STARTER</span><span><span className="live-dot"/>7-DAY FREE TRIAL</span></div><div className="premium-price-number"><span>RM</span>99<small>/ month</small></div><p>One business. One private AI assistant.</p><ul>{['30 plan generations or AI revisions / month','500 private test replies / month','Business knowledge and editable FAQs','Plan approval and complete version history'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><button className="premium-cta price-cta" onClick={onStart}>Start your seven-day trial <ArrowUpRight size={18}/></button><p className="price-disclosure">RM0 today, then RM99/month. Card required. Renews automatically; cancel renewal in your workspace.<br/><br/>Trial: up to 3 generations, 50 replies, US$0.50 AI budget.<br/>Paid: US$5 AI budget/month. The first reached limit applies.</p></div></div></div></section>
      <section className="cinema-faq premium-section" id="faq"><div data-reveal><span className="small-caps">A LITTLE CLARITY</span><h2>Good questions.<br/><span>Clear answers.</span></h2></div><div className="premium-faq-list" data-reveal>{faqs.map(([q,a],i)=><div className="premium-faq-item" key={q}><h3><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i} aria-controls={`answer-${i}`}>{q}<Plus className={faq===i?'faq-open':''} size={20}/></button></h3><div id={`answer-${i}`} hidden={faq!==i}><p>{a}</p></div></div>)}</div></section>
      <section className="final-invitation premium-section"><span className="small-caps" data-reveal>THE NEXT CONVERSATION IS YOURS.</span><div data-reveal><h2>Let's make it<br/><span>mean something.</span></h2><button className="invitation-arrow" title="Start with your business" aria-label="Start with your business" onClick={onStart}><ArrowUpRight strokeWidth={1.3}/></button></div><a className="premium-text-link" href="#lumo-prompt">Start with one idea <ArrowRight size={17}/></a></section>
    </main><footer className="premium-footer"><div className="footer-top"><a className="premium-logo" href="/">lumo<span>.</span></a><p>Intelligence, with your intention.</p><a href="#lumo-prompt" className="premium-text-link">Back to the beginning <ArrowUpRight size={15}/></a></div><div className="footer-wordmark" aria-hidden="true">lumo<span>.</span></div><div className="footer-bottom"><span>&copy; {new Date().getFullYear()} Lumo</span><span>Private planning. Better conversations.</span><div><a href="/terms">Terms</a><a href="/privacy">Privacy</a><button onClick={onTheme}>{theme==='dark'?<Sun size={13}/>:<Moon size={13}/>} {theme==='dark'?'Light':'Dark'} mode</button></div></div></footer>
  </div>;
}
