import React,{useEffect,useState} from 'react';
import {Check,Clock,LoaderCircle,Pencil,Plus,Save,Search,ShieldCheck} from 'lucide-react';
import {api} from './api';
import {Modal} from './Modal';
import {offerInput,followupInput,priceToSen,rm,type Offer,type SalesState} from '../shared/sales';
import {sampleOperations} from './operations-sample';
import './operations.css';
import './sales.css';
const key='lumo-sales-sample-v1';
function sampleState():SalesState{try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved?.version===1&&Array.isArray(saved.state?.offers)&&Array.isArray(saved.state?.followups)&&Array.isArray(saved.state?.leads))return saved.state;}catch{}const now=new Date().toISOString();return {offers:[{id:crypto.randomUUID(),name:'Starter consultation',description:'Understand your requirements and recommend a suitable solution.',price_sen:9900,terms:'One consultation. No purchase obligation.',approved_at:now,updated_at:now}],followups:[],leads:sampleOperations().leads.map(({id,name})=>({id,name}))};}
export function Sales({tab,sample,workspaceId}:{tab:'catalogue'|'followups';sample:boolean;workspaceId:string}){
 const [data,setData]=useState<SalesState|null>(sample?sampleState:null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all');
 const [editor,setEditor]=useState<Offer|true|null>(null),[taskEditor,setTaskEditor]=useState(false);
 async function refresh(){setData(await api<SalesState>('/sales'));}
 useEffect(()=>{let active=true;setError('');setSearch('');setFilter('all');if(!sample){setData(null);setBusy(true);api<SalesState>('/sales').then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});}else{setData(d=>({...d!,leads:(()=>{try{const ops=JSON.parse(localStorage.getItem('lumo-operations-sample-v1')??'null');if(ops?.state?.leads)return ops.state.leads.map(({id,name}:{id:string;name:string})=>({id,name}));}catch{}return sampleOperations().leads.map(({id,name})=>({id,name}));})()}));}return()=>{active=false;};},[sample,workspaceId,tab]);
 useEffect(()=>{if(sample&&data)localStorage.setItem(key,JSON.stringify({version:1,state:data}));},[sample,data]);
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function saveOffer(input:unknown){await action(async()=>{const values=offerInput.parse(input);const id=editor&&editor!==true?editor.id:null;if(sample)setData(d=>({...d!,offers:id?d!.offers.map(o=>o.id===id?{...o,...values,approved_at:null,updated_at:new Date().toISOString()}:o):[{...values,id:crypto.randomUUID(),approved_at:null,updated_at:new Date().toISOString()},...d!.offers]}));else{await api(`/sales/offers${id?`/${id}`:''}`,values,id?'PUT':'POST');await refresh();}setEditor(null);setNotice('Draft saved. Review and approve before the assistant can use this offer.');});}
 async function approve(o:Offer){await action(async()=>{if(sample)setData(d=>({...d!,offers:d!.offers.map(item=>item.id===o.id?{...item,approved_at:new Date().toISOString()}:item)}));else{await api(`/sales/offers/${o.id}/approval`,{expected_updated_at:o.updated_at});await refresh();}setNotice('Offer approved for private planning and testing.');});}
 const offers=data?.offers.filter(o=>`${o.name} ${o.description}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='approved'?!!o.approved_at:!o.approved_at)))??[];
 const tasks=data?.followups.filter(t=>`${t.title} ${data.leads.find(l=>l.id===t.lead_id)?.name??''}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='overdue'?t.status==='pending'&&Date.parse(t.due_at)<Date.now():t.status===filter)))??[];
 return <div className="operations"><div className="page-heading"><div><span className="overline">SALES WORKSPACE</span><h1>{tab==='catalogue'?'Sales catalogue':'Follow-ups'}</h1><p>{tab==='catalogue'?'Your approved offers, exact RM prices, and selling terms.':'A clear next step for every buying conversation.'}</p></div><button className="button primary small" disabled={busy||!data||(tab==='followups'&&!data.leads.length)} onClick={()=>{setError('');tab==='catalogue'?setEditor(true):setTaskEditor(true);}}><Plus size={16}/>{tab==='catalogue'?'Add offer':'Add follow-up'}</button></div>
 <div aria-live="polite">{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success"><Check size={16}/>{notice}</div>}</div>
 {sample&&<p className="ops-caption">Sample records only. No AI calls or customer messages are sent.</p>}
 {!data?<div className="ops-empty">{busy?<LoaderCircle className="spin"/>:<><h2>Sales records unavailable</h2><p>The server needs database access and the sales migration.</p><button className="button secondary" onClick={()=>action(refresh)}>Retry</button></>}</div>:<><div className="ops-toolbar"><label className="ops-search"><Search size={16}/><input aria-label="Search sales records" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="ops-filter">Status<select value={filter} onChange={e=>setFilter(e.target.value)}>{(tab==='catalogue'?['all','draft','approved']:['all','pending','overdue','completed','cancelled']).map(s=><option key={s} value={s}>{s.charAt(0).toUpperCase()+s.slice(1)}</option>)}</select></label></div>
 {tab==='catalogue'?<><div className="ops-caption">Editing an offer removes its approval. Private AI supports up to 30 approved offers; saved drafts are not used.</div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Offer</th><th>Price</th><th>Review</th><th>Actions</th></tr></thead><tbody>{offers.map(o=><tr key={o.id}><td><strong>{o.name}</strong><small className="sales-copy">{o.description}</small><small className="sales-copy">{o.terms}</small></td><td>{rm(o.price_sen)}</td><td><span className={`ops-pill ${o.approved_at?'confirmed':'requested'}`}>{o.approved_at?'Approved':'Draft'}</span></td><td><div className="sales-actions"><button className="icon-button" aria-label={`Edit ${o.name}`} title="Edit offer" disabled={busy} onClick={()=>{setError('');setEditor(o);}}><Pencil size={16}/></button>{!o.approved_at&&<button className="button secondary small" disabled={busy} onClick={()=>approve(o)}><ShieldCheck size={16}/>Approve</button>}</div></td></tr>)}</tbody></table></div>{!offers.length&&<div className="ops-empty"><h2>No offers to show</h2><p>Add a product, package, or service.</p></div>}</>:<><div className="ops-caption">Internal tasks only. Times are shown in Malaysia time. Automatic reminders and customer delivery are not activated.</div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Lead / next step</th><th>Due</th><th>Status</th><th>Update</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><strong>{data.leads.find(l=>l.id===t.lead_id)?.name??'Lead outside loaded list'}</strong><small className="sales-copy">{t.title}</small><small className="sales-copy">{t.notes}</small></td><td>{new Intl.DateTimeFormat('en-MY',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kuala_Lumpur'}).format(new Date(t.due_at))}{t.status==='pending'&&Date.parse(t.due_at)<Date.now()&&<small className="sales-overdue">Overdue</small>}</td><td>{t.status}</td><td><select aria-label={`Status for ${t.title}`} value={t.status} disabled={busy} onChange={e=>{const status=e.target.value as typeof t.status;action(async()=>{if(sample)setData(d=>({...d!,followups:d!.followups.map(item=>item.id===t.id?{...item,status}:item)}));else{await api(`/sales/followups/${t.id}`,{status},'PATCH');await refresh();}setNotice('Task updated. No customer message sent.');});}}>{['pending','completed','cancelled'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>{!tasks.length&&<div className="ops-empty"><Clock size={28}/><h2>No follow-ups to show</h2><p>{data.leads.length?'Add a next step for a lead.':'Add a lead first in Leads.'}</p></div>}</>}
 <p className="ops-caption">Showing up to 200 records per view.</p></>}
 {editor&&<OfferEditor value={editor===true?undefined:editor} busy={busy} error={error} close={()=>setEditor(null)} save={saveOffer}/>}
 {taskEditor&&data&&<Modal title="New follow-up" onClose={()=>setTaskEditor(false)}><form className="ops-modal-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);action(async()=>{const values=followupInput.parse({lead_id:form.get('lead_id'),title:form.get('title'),notes:form.get('notes'),due_at:new Date(String(form.get('due'))).toISOString()});if(sample)setData(d=>({...d!,followups:[{...values,id:crypto.randomUUID(),status:'pending',updated_at:new Date().toISOString()},...d!.followups]}));else{await api('/sales/followups',values);await refresh();}setTaskEditor(false);setNotice('Internal follow-up saved. No customer message sent.');});}}>{error&&<p className="alert error">{error}</p>}<label>Lead<select name="lead_id">{data.leads.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label>Next step<input name="title" required maxLength={200}/></label><label>Due ({Intl.DateTimeFormat().resolvedOptions().timeZone})<input type="datetime-local" name="due" required/></label><label>Internal notes<textarea name="notes" maxLength={1000}/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setTaskEditor(false)}>Cancel</button><button className="button primary" disabled={busy}><Save size={16}/>Save task</button></div></form></Modal>}
 </div>;
}
function OfferEditor({value,busy,error,close,save}:{value?:Offer;busy:boolean;error:string;close:()=>void;save:(input:unknown)=>Promise<void>}){
 const [localError,setLocalError]=useState('');
 return <Modal title={value?'Edit offer':'New offer'} onClose={close}><form className="ops-modal-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setLocalError('');try{save({name:f.get('name'),description:f.get('description'),terms:f.get('terms'),price_sen:priceToSen(String(f.get('price')))});}catch(e){setLocalError((e as Error).message);}}}>{(error||localError)&&<p className="alert error" role="alert">{localError||error}</p>}<label>Offer name<input name="name" required maxLength={120} defaultValue={value?.name}/></label><label>Price (RM)<input name="price" inputMode="decimal" required defaultValue={value?(value.price_sen/100).toFixed(2):''}/></label><label>Description<textarea name="description" maxLength={1000} defaultValue={value?.description}/></label><label>Terms and exclusions<textarea name="terms" maxLength={1000} defaultValue={value?.terms}/></label><p className="ops-muted">Saved as a draft. Review and approve the offer separately.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button primary" disabled={busy}><Save size={16}/>Save draft</button></div></form></Modal>;
}
