import React,{useEffect,useRef,useState} from 'react';
import {signOut} from 'firebase/auth';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,CheckCheck,ChevronDown,Clock3,CreditCard,Download,FileText,GitBranch,History,Info,LoaderCircle,LockKeyhole,LogOut,MessageSquare,MoreHorizontal,Pencil,Plus,RotateCcw,Save,Send,ShieldCheck,Sparkles,X,Menu,PanelLeftOpen} from 'lucide-react';
import {type ChatMessage,type Knowledge,type Plan,type PlanContent,type WorkspaceState,LIMITS,planSchema,knowledgeSchema} from '../shared/schema';
import {api,auth,readDraft,saveDraft,type PublicConfig} from './api';
import {sampleState,sampleReply} from './sample';
import {WorkspaceNavigation,workspaceTabs,type WorkspaceTab} from './WorkspaceNavigation';
import {Operations,type OperationsTab} from './Operations';
import {Modal} from './Modal';

type Tab=WorkspaceTab;
const tabs=workspaceTabs;
const operationsTabs:Tab[]=['overview','leads','appointments','inbox','connections','settings'];
function initialSample(){try{const stored=JSON.parse(localStorage.getItem('lumo-sample-v1')??'null');if(stored?.workspace?.id==='sample'&&stored.plans?.length)return stored as WorkspaceState;}catch{}return sampleState();}
export function Workspace({sample,config,onStart}:{sample:boolean;config:PublicConfig|null;onStart:()=>void}){
  const [state,setState]=useState<WorkspaceState|null>(sample?initialSample:null);
  const [tab,setTabState]=useState<Tab>(()=>{const requested=new URLSearchParams(location.search).get('tab');return tabs.some(t=>t.id===requested)?requested as Tab:!sample&&readDraft().trim()?'plan':'overview';});
  const [collapsed,setCollapsed]=useState(()=>{try{return localStorage.getItem('lumo-sidebar-collapsed')==='true';}catch{return false;}});
  const [mobileOpen,setMobileOpen]=useState(false);
  const [mobileViewport,setMobileViewport]=useState(()=>matchMedia('(max-width: 800px)').matches);
  const navigationToggle=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const media=matchMedia('(max-width: 800px)');function update(){setMobileViewport(media.matches);if(!media.matches)setMobileOpen(false);}media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  useEffect(()=>{if(!mobileOpen)return;document.querySelector<HTMLButtonElement>('.ws-close')?.focus();return()=>navigationToggle.current?.focus();},[mobileOpen]);
  function setTab(next:Tab){setTabState(next);setMobileOpen(false);const url=new URL(location.href);url.searchParams.set('tab',next);history.replaceState(null,'',url);}
  function toggleNavigation(){if(matchMedia('(max-width: 800px)').matches)setMobileOpen(v=>!v);else setCollapsed(v=>!v);}
  useEffect(()=>{try{localStorage.setItem('lumo-sidebar-collapsed',String(collapsed));}catch{}},[collapsed]);
  useEffect(()=>{function close(e:KeyboardEvent){if(e.key==='Escape')setMobileOpen(false);}window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  const [selected,setSelected]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [prompt,setPrompt]=useState(readDraft);const [knowledge,setKnowledge]=useState<Knowledge|null>(null);
  const [editing,setEditing]=useState(false);const [edit,setEdit]=useState<PlanContent|null>(null);const [cancelOpen,setCancelOpen]=useState(false);
  const [message,setMessage]=useState('');const [messages,setMessages]=useState<ChatMessage[]>([]);const [conversationId,setConversationId]=useState<string|null>(null);
  const chatBottom=useRef<HTMLDivElement>(null);
  const plan=state?.plans.find(p=>p.id===selected)??state?.plans[0];
  const approved=!!plan?.approved_at;const billing=state?.billing;const allowance=LIMITS[billing?.tier??'paid'];
  async function refresh(){const data=await api<WorkspaceState&{syncWarning?:string}>('/workspace');setState(data);if(data.syncWarning)setNotice(data.syncWarning);return data;}
  useEffect(()=>{if(!sample){setBusy('load');refresh().catch(e=>setError(e.message)).finally(()=>setBusy(''));}},[sample]);
  useEffect(()=>{if(state&&!knowledge)setKnowledge(state.knowledge);if(sample&&state)try{localStorage.setItem('lumo-sample-v1',JSON.stringify(state));}catch{}},[state]);
  useEffect(()=>{setMessages([]);setConversationId(null);setMessage('');setEditing(false);if(!sample&&plan?.id){api(`/chat/${plan.id}`).then(data=>{setMessages(data.messages);setConversationId(data.id);}).catch(e=>setError(e.message));}},[plan?.id,sample]);
  useEffect(()=>{chatBottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
  async function action(name:string,fn:()=>Promise<void>){setBusy(name);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  function addPlan(p:Plan){setState(s=>({...s!,plans:[p,...s!.plans]}));setSelected(p.id);setEditing(false);}
  function changeKnowledge<K extends keyof Knowledge>(key:K,value:Knowledge[K]){setKnowledge(k=>({...k!,[key]:value}));}
  async function saveKnowledge(){await action('save',async()=>{const content=knowledgeSchema.parse(knowledge);if(sample)setState(s=>({...s!,knowledge:content,workspace:{...s!.workspace,name:content.name||'My business'}}));else{await api('/knowledge',content,'PUT');await refresh();}setNotice('Business knowledge saved.');});}
  async function generate(){
    saveDraft(prompt);
    if(sample||!billing?.access){onStart();return;}
    await action('generate',async()=>{const p=await api<Plan>('/plans/generate',{prompt});await refresh();setSelected(p.id);setNotice('New plan created. Review it before approval.');});
  }
  async function saveVersion(){await action('version',async()=>{
    const content=planSchema.parse(edit);
    if(sample)addPlan({id:`sample-${Date.now()}`,version:Math.max(...state!.plans.map(p=>p.version))+1,content,approved_at:null,created_at:new Date().toISOString()});
    else{const p=await api<Plan>('/plans',content);await refresh();setSelected(p.id);setEditing(false);}
    setNotice('Saved as a new draft. Previous versions are preserved.');
  });}
  async function approve(){if(!plan)return;await action('approve',async()=>{if(sample)setState(s=>({...s!,plans:s!.plans.map(p=>p.id===plan.id?{...p,approved_at:new Date().toISOString()}:p)}));else{await api(`/plans/${plan.id}/approve`,{});await refresh();}setNotice('Plan approved. Your test chat is ready.');});}
  async function send(e:React.FormEvent){e.preventDefault();if(!message.trim()||!plan||!approved)return;if(!sample&&!billing?.access){onStart();return;}const text=message.trim();await action('chat',async()=>{if(sample)setMessages(m=>[...m,{role:'user',text},{role:'model',text:sampleReply(text)}]);else{const data=await api('/chat',{planId:plan.id,conversationId,message:text});setMessages(data.messages);setConversationId(data.id);await refresh();}setMessage('');});}
  async function portal(){await action('portal',async()=>{const data=await api('/billing/portal',{});location.assign(data.url);});}
  function exportPlan(){if(!plan)return;const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`lumo-plan-v${plan.version}.json`;a.click();URL.revokeObjectURL(url);}
  const date=billing?.periodEnd?new Date(billing.periodEnd).toLocaleDateString('en-MY',{day:'numeric',month:'short',year:'numeric'}):null;
  return <div className="workspace-shell">
    <WorkspaceNavigation tab={tab} collapsed={collapsed} mobileOpen={mobileOpen} name={state?.workspace.name||'My business'} sample={sample} onNavigate={next=>{setTab(next);setError('');setNotice('');}} onCollapse={()=>setCollapsed(true)} onClose={()=>setMobileOpen(false)} onSignOut={async()=>{if(auth)await signOut(auth);location.assign('/');}}/>
    <div className="workspace-main" inert={mobileOpen||undefined}><header className="workspace-header"><div className="ws-header-title"><button ref={navigationToggle} className="icon-button" title="Toggle navigation" aria-label="Toggle workspace navigation" aria-controls="workspace-navigation" aria-expanded={mobileViewport?mobileOpen:!collapsed} onClick={toggleNavigation}>{collapsed?<PanelLeftOpen size={18}/>:<Menu size={18}/>}</button><span>Workspace <span className="breadcrumb-slash">/</span> <strong>{tabs.find(t=>t.id===tab)?.label}</strong></span></div><div><span className="private-label"><LockKeyhole size={13}/>Private</span><span className="user-avatar">{state?.workspace.name.charAt(0)||'L'}</span></div></header>
      {sample&&<div className="sample-banner"><Info size={16}/><span>Sample workspace <span className="sample-banner-detail">&middot; Fixed example data. No live AI, account, or payment.</span></span><button onClick={onStart}>Create my assistant <ArrowRight size={14}/></button></div>}
      {!sample&&!billing?.access&&state&&<div className="sample-banner locked-banner"><LockKeyhole size={16}/><span>{billing?.review?'Trial eligibility needs review. Renewal has been stopped.':'Your work is saved. Start a trial or subscription to unlock AI.'}</span><button onClick={billing?.review?portal:onStart}>{billing?.review?'Manage billing':'Unlock Lumo'}<ArrowRight size={14}/></button></div>}
      <div className="workspace-content">
        <div aria-live="polite">{error&&<div className="alert error"><Info size={17}/>{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="alert success"><Check size={17}/>{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={15}/></button></div>}</div>
        {busy==='load'&&<div className="empty-state"><LoaderCircle size={28} className="spin"/><h2>Opening your workspace</h2></div>}
        {!state&&busy!=='load'&&<div className="empty-state"><LockKeyhole size={32}/><h2>Your workspace is waiting</h2><p>Sign in with a verified email or phone number to access your saved work.</p><button className="button primary" onClick={onStart}>Sign in <ArrowRight size={16}/></button></div>}
        {state&&operationsTabs.includes(tab)&&<Operations tab={tab as OperationsTab} sample={sample} workspace={state} config={config} navigate={next=>setTab(next as Tab)}/>}
        {state&&tab==='knowledge'&&knowledge&&<><div className="page-heading"><div><span className="overline">THE FOUNDATION</span><h1>Business knowledge</h1><p>The facts and boundaries behind every answer.</p></div><button className="button primary" disabled={!!busy} onClick={saveKnowledge}><Save size={16}/>Save changes</button></div><div className="knowledge-layout"><form className="knowledge-form" onSubmit={e=>{e.preventDefault();saveKnowledge();}}><label>Business name<input maxLength={100} value={knowledge.name} onChange={e=>changeKnowledge('name',e.target.value)} placeholder="Your business name"/></label><label>About your business<textarea rows={6} maxLength={5000} value={knowledge.business} onChange={e=>changeKnowledge('business',e.target.value)} placeholder="Services, prices, location, opening hours, and confirmed policies"/><span className="field-meta">Business facts, services, prices, and opening hours<span>{knowledge.business.length}/5,000</span></span></label><label>Frequently asked questions<textarea rows={6} maxLength={5000} value={knowledge.faq} onChange={e=>changeKnowledge('faq',e.target.value)} placeholder="Add common questions with their verified answers."/></label><div className="form-two"><label>Conversation language<select value={knowledge.language} onChange={e=>changeKnowledge('language',e.target.value as Knowledge['language'])}><option>English</option><option>Bahasa Melayu</option><option>English + Bahasa Melayu</option></select></label></div><label>Human handoff instructions<textarea rows={3} maxLength={500} value={knowledge.handoff} onChange={e=>changeKnowledge('handoff',e.target.value)} placeholder="What should happen when your assistant cannot answer?"/></label></form><aside className="context-note"><BookOpen size={22}/><h3>Good answers start with good facts.</h3><p>Only include information your team can stand behind. Unknown prices or appointment times should go to a human.</p><hr/><span className="badge neutral">Private knowledge</span><p>Your business information belongs to this workspace.</p></aside></div></>}
        {state&&tab==='plan'&&<><div className="page-heading"><div><span className="overline">SHAPE THE CONVERSATION</span><h1>Conversation plan</h1><p>A clear path from the first hello to the right next step.</p></div>{plan&&<div className="heading-actions"><button className="icon-button" title="Download plan" aria-label="Download plan" onClick={exportPlan}><Download size={18}/></button><label className="version-select"><History size={15}/><select aria-label="Plan version" value={plan.id} disabled={!!busy} onChange={e=>setSelected(e.target.value)}>{state.plans.map(p=><option key={p.id} value={p.id}>Version {p.version}{p.approved_at?' - approved':' - draft'}</option>)}</select></label></div>}</div>
          <div className="plan-prompt"><div><Sparkles size={17}/><strong>{plan?'A new idea or a refinement?':'Start with your business idea'}</strong></div><textarea aria-label="Plan prompt" maxLength={3000} value={prompt} onChange={e=>{setPrompt(e.target.value);saveDraft(e.target.value);}} placeholder="Describe your business, what your assistant should ask, and what a good outcome looks like..."/><div className="plan-prompt-footer"><span>{sample?'Generate your own plan with a verified trial or subscription.':`${state.usage.plans} / ${allowance.plans} generations used`}</span><button className="button primary small" disabled={!!busy||(!sample&&prompt.trim().length<10)} onClick={generate}>{busy==='generate'?<LoaderCircle className="spin" size={15}/>:<Sparkles size={15}/>}Generate plan</button></div></div>
          {plan?<><div className="plan-title"><div><h2>{plan.content.title}</h2><span className={`badge ${approved?'green':'amber'}`}>{approved?<CheckCheck size={12}/>:<Pencil size={12}/>} {approved?'Approved for testing':'Draft - review before testing'}</span></div><div className="heading-actions">{editing?<><button className="button secondary small" onClick={()=>setEditing(false)}>Cancel</button><button className="button primary small" onClick={saveVersion} disabled={!!busy}><Save size={15}/>Save new version</button></>:<button className="button secondary small" onClick={()=>{setEdit(structuredClone(plan.content));setEditing(true);}}><Pencil size={15}/>Edit plan</button>}</div></div>
          {editing&&edit?<div className="plan-editor"><label>Plan name<input value={edit.title} maxLength={120} onChange={e=>setEdit({...edit,title:e.target.value})}/></label>{(['greeting','questions','rules','fallback','handoff','leadFields'] as const).map(key=><label key={key}>{({greeting:'Greeting',questions:'Qualification questions (one per line)',rules:'Business rules (one per line)',fallback:'Fallback answer',handoff:'Handoff conditions (one per line)',leadFields:'Lead fields (one per line)'})[key]}<textarea rows={Array.isArray(edit[key])?4:3} value={Array.isArray(edit[key])?(edit[key] as string[]).join('\n'):edit[key] as string} onChange={e=>setEdit({...edit,[key]:Array.isArray(edit[key])?e.target.value.split('\n'):e.target.value})}/></label>)}</div>:<div className="plan-layout"><div className="plan-flow">{[{title:'A warm welcome',tag:'GREETING',icon:MessageSquare,body:<p>{plan.content.greeting}</p>},{title:'Understand the customer',tag:'QUALIFY',icon:GitBranch,body:<ol>{plan.content.questions.map((q,i)=><li key={i}>{q}</li>)}</ol>},{title:'Keep the right boundaries',tag:'BUSINESS RULES',icon:ShieldCheck,body:<ul>{plan.content.rules.map((q,i)=><li key={i}>{q}</li>)}</ul>},{title:'Leave room for a human',tag:'HANDOFF',icon:ArrowUpRight,body:<><p className="fallback">{plan.content.fallback}</p><ul>{plan.content.handoff.map((q,i)=><li key={i}>{q}</li>)}</ul></>}].map((section,i)=><div className="plan-step" key={section.title}><div className="step-rail"><span>{i+1}</span></div><article><div className="plan-step-heading"><span className="overline">{section.tag}</span><section.icon size={17}/></div><h3>{section.title}</h3>{section.body}</article></div>)}</div><aside className="plan-summary"><h3>At a glance</h3><dl><dt>Assistant</dt><dd>{state.workspace.name}</dd><dt>Language</dt><dd>{state.knowledge.language}</dd><dt>Lead details</dt><dd className="lead-tags">{plan.content.leadFields.map((f,i)=><span key={i}>{f}</span>)}</dd></dl><div className="approval-box"><ShieldCheck size={21}/><strong>{approved?'Ready for a test run':'Your approval comes first'}</strong><p>{approved?'This version is approved. Try a conversation and see where it leads.':'Review the facts and rules before testing this version.'}</p><button disabled={!!busy} className="button primary full" onClick={approved?()=>setTab('chat'):approve}>{approved?'Open test chat':'Approve this plan'}{approved?<ArrowRight size={15}/>:<Check size={15}/>}</button></div></aside></div>}</>:<div className="empty-state"><GitBranch size={32}/><h2>Your first plan starts here</h2><p>Add business knowledge and describe the conversation above.</p><button className="button secondary" onClick={()=>setTab('knowledge')}>Add business knowledge <ArrowRight size={15}/></button></div>}
        </>}
        {state&&tab==='chat'&&<><div className="page-heading"><div><span className="overline">A PRIVATE REHEARSAL</span><h1>Test chat</h1><p>{sample?'Fixed sample responses. No live AI or real bookings.':'Put your approved conversation plan to the test.'}</p></div><button className="button secondary small" disabled={!!busy} onClick={()=>{setMessages([]);setConversationId(null);setNotice('New test conversation started.');}}><Plus size={16}/>New conversation</button></div><div className="test-layout"><div className="chat-panel"><div className="chat-panel-head"><span className="business-avatar">{state.workspace.name.charAt(0)}</span><div><strong>{state.workspace.name} assistant</strong><small>{sample?'Fixed example':`Version ${plan?.version??'-'}`} &middot; {approved?'Approved':'Awaiting approval'}</small></div><span className={`badge ${sample?'neutral':'green'}`}>{sample?'Sample':'Private test'}</span></div><div className="chat-scroll" aria-live="polite">{!approved?<div className="empty-state"><LockKeyhole size={28}/><h2>Review. Approve. Then test.</h2><p>Approve a conversation plan before starting a test.</p><button className="button primary" onClick={()=>setTab('plan')}>Review plan <ArrowRight size={16}/></button></div>:<><div className="chat-date">{sample?'SAMPLE CONVERSATION':'PRIVATE CONVERSATION'}</div><div className="chat-message model"><span className="mini-logo">L</span><div>{plan?.content.greeting}</div></div>{messages.map((m,i)=><div key={i} className={`chat-message ${m.role}`}>{m.role==='model'&&<span className="mini-logo">L</span>}<div>{m.text}</div></div>)}{busy==='chat'&&<div className="chat-message model"><span className="mini-logo">L</span><div><LoaderCircle className="spin" size={16}/></div></div>}<div ref={chatBottom}/></>}</div><form className="chat-form" onSubmit={send}><input aria-label="Test message" placeholder={approved?'Ask as a customer...':'Approve a plan to start'} value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} disabled={!approved||!!busy}/><button className="icon-button send-button" type="submit" disabled={!approved||!!busy||!message.trim()} aria-label="Send message" title="Send message"><Send size={18}/></button></form></div><aside className="test-aside"><h3>A customer's point of view</h3><p>Explore the questions your business hears every day.</p>{['How much is a haircut?','What are your opening hours?','Can I book for tomorrow?'].map(q=><button key={q} disabled={!approved} onClick={()=>setMessage(q)}>{q}<ArrowUpRight size={14}/></button>)}<hr/><div className="secure-line"><LockKeyhole size={14}/>Only visible in your workspace</div><p className="fine">Testing does not send messages to customers, charge cards, or confirm bookings.</p></aside></div></>}
        {state&&tab==='billing'&&<><div className="page-heading"><div><span className="overline">CLEAR LIMITS. NO SURPRISES.</span><h1>Usage & billing</h1><p>Your subscription, allowance, and renewal in one place.</p></div>{!sample&&<button className="button secondary small" disabled={!!busy} onClick={()=>action('refresh',async()=>{await refresh();setNotice('Billing refreshed.');})}><RotateCcw size={15}/>Refresh status</button>}</div><section className="billing-overview"><div><span className="badge">{sample?'Sample - no subscription':billing?.status==='trialing'?'Seven-day trial':billing?.status==='active'?'Active subscription':'Not subscribed'}</span><h2>Lumo Starter</h2><p>One private assistant for your business.</p></div><div><strong className="billing-price">RM99<small>/month</small></strong><p>{sample?'No card connected or charged.':date?`${billing?.cancelAtEnd?'Access ends':billing?.tier==='trial'?'Trial ends':'Period ends'} ${date}`:'Start with a seven-day card-required trial.'}</p></div></section><div className="usage-grid">{[{label:'Plan generations',value:state.usage.plans,max:allowance.plans,icon:GitBranch},{label:'Test replies',value:state.usage.replies,max:allowance.replies,icon:MessageSquare},{label:'AI budget (USD)',value:state.usage.costMicros/1000000,max:allowance.costMicros/1000000,icon:Sparkles}].map(x=><article className="usage-meter" key={x.label}><div><span>{x.label}</span><x.icon size={17}/></div><strong>{x.value.toFixed(x.label.includes('budget')?2:0)}<small> / {x.max}</small></strong><progress value={x.value} max={x.max} aria-label={x.label}/><small>{sample?'Sample figures only':billing?.tier==='trial'?'Total trial allowance':'Per billing month'}</small></article>)}</div><div className="billing-detail"><h3>You're in control</h3><p>AI stops at the first reached generation, reply, or cost limit. There are no automatic overage charges. Failed renewal pauses new AI work; your saved plans remain accessible.</p><div className="billing-actions">{sample||!billing?.access&&!billing?.trialUsed?<button className="button primary" onClick={onStart}>Start seven-day trial <ArrowRight size={16}/></button>:<><button className="button secondary" disabled={!!busy} onClick={portal}><CreditCard size={16}/>Manage payment method</button>{!billing?.cancelAtEnd&&<button className="button danger-outline" disabled={!!busy} onClick={()=>setCancelOpen(true)}>Cancel renewal</button>}</>}<a href="/terms">Terms of service <ArrowUpRight size={13}/></a></div>{billing?.cancelAtEnd&&<div className="notice"><Check size={16}/>Renewal cancelled. Access continues until {date}.</div>}{config?.testMode&&<p className="fine">Stripe is in test mode. Live payments are disabled.</p>}</div></>}
      </div><footer className="workspace-footer"><span><LockKeyhole size={12}/>Private by design</span><div><a href="/terms">Terms</a><a href="/privacy">Privacy</a><span>Lumo</span></div></footer>
    </div>
    {cancelOpen&&<Modal title="Cancel your renewal?" onClose={()=>setCancelOpen(false)}><p>Your access continues until {date}. After that, saved work remains available, but new AI generation and replies stop.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setCancelOpen(false)}>Keep subscription</button><button disabled={!!busy} className="button danger" onClick={()=>action('cancel',async()=>{await api('/billing/cancel',{});await refresh();setCancelOpen(false);setNotice('Renewal cancelled.');})}>Cancel renewal</button></div></Modal>}
  </div>;
}
